#! /bin/bash
#file /home/jager/.config/bspwm/bspwmrc

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-  #
#                                                                              #
# - - - - - - - - - - - - - - - !!! WARNING !!! - - - - - - - - - - - - - - -  #
#                                                                              #
#        BINARY SPACE PARTITIONING WINDOW MANAGER INITIALIZATION SCRIPT        #
#                                                                              #
#  MAKE SURE ALL PROCESSES ARE STARTED IN THE BACKGROUND OR EXIT IMMEDIATELY   #
#                                                                              #
#               COMMANDS THAT DO NOT EXIT WILL BREAK THIS SCRIPT               #
#                                                                              #
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-  #


# Everything is inside of main so I can redirect the output to a file.
function main(){
# Const
# Home directory path:
HOME="/home/jager"

# Var
# Number of monitors.
MONITOR_COUNT=$(bspc query -M | wc -l)

# Uncomment to make sure any notify-send or similar graphical programs can
#+display to the screen correctly when run from this script.
export DISPLAY=:0
export XAUTHORITY='/home/jager/.Xauthority'

# ============================================================================ #
#                   Startup Applications and Scripts - Pre-Up                  #
# ============================================================================ #
# ---------------------------------------------------------------------------- #
#                                 Daemons Only                                 #
# ---------------------------------------------------------------------------- #
# Set wallpaper
#${HOME}/Documents/Code/Bash/reset_wallpaper_with_monitor_check                &

# Start SXHKD keybinder.
# -f: Motion event frequency setting.
# Fixes some laggy movement with mouse controls.
#sxhkd																		   &

# ============================================================================ #
#                                 BSPWM Settings                               #
# ============================================================================ #
# ---------------------------------------------------------------------------- #
#                                 Window Settings                              #
# ---------------------------------------------------------------------------- #
# The next few commands need to be run sequentially as the following commands
#+rely on them.
# Run pywal, sets wallpaper and matches themes to it, then generate steam theme
#+based on wal theme. The grep is to prevent the escape characters wal creates
#+being written to the log file.
function source_colours(){
	wal -Rq | grep -v '\e'
	wal-steam -d | grep -i error
	# Source the colors from Wal.
	. "${HOME}/.cache/wal/colors.sh"
	# Set the border colors based on Wal's colour selections.
	# Color of the border of an unfocused window.
	bspc config normal_border_color		"${color1}"
	# Color of the border of a focused window of an unfocused monitor.
	bspc config active_border_color		"${color2}"
	# Color of the border of a focused window of a focused monitor.
	bspc config focused_border_color	"${color15}"
	# Color of the node --presel-{dir,ratio} message feedback area.
	bspc config presel_feedback_color	"${color15}"
}
source_colours &
# BSPWM settings
# Window border width.
bspc config border_width					  1								   &
# Size of the gap that separates windows.
bspc config window_gap                        5                                &
# Default split ratio.
bspc config split_ratio                       0.50                             &
# Set the layout to monocle if there’s only one tiled window in the tree.
bspc config single_monocle                    true                             &
# Remove borders of tiled windows for the monocle desktop layout.
bspc config borderless_monocle                true                             &
# Remove gaps of tiled windows for the monocle desktop layout.
bspc config gapless_monocle                   true                             &
# When focusing a monitor, put the pointer at its center.
bspc config pointer_follows_monitor           true                             &
# Ignore focus requests from applications.
bspc config ignore_ewmh_focus                true                              &
# Setup pointer keybinds the new way.
bspc config pointer_modifier mod4                                              &
bspc config pointer_action1 move                                               &
bspc config pointer_action2 resize_corner                                      &
bspc config pointer_action3 none											   &


# ---------------------------------------------------------------------------- #
#                                Create Desktops                               #
# ---------------------------------------------------------------------------- #
# Symbols storage
#            

# Give every monitor 10 workspaces.
monindex=${MONITOR_COUNT}
while  [[ $monindex != 0 ]];do
	bspc monitor ^"$monindex" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'
	((--monindex))
done

# Monitor #2
#if [[ $MONITOR_COUNT -gt '1' ]]; then
	# This line was for the laptop this script was originially written on.
    #/home/jager/Documents/Code/Bash/monitor_DVI-0_desktops &
#fi

# ---------------------------------------------------------------------------- #
#                           Application Specific Rules
# ---------------------------------------------------------------------------- #
# Use this command to find window class:
# xprop | awk '/WM_CLASS/{print $4}'

# Most desktops are free for use by any program, some I will reserve for
# specific applications.
# 1 - 5: are all for anything, including VMs.
# 6: for eMail and messaging applications, steam chat windows will probably
#+be left on the steam desktop as they're usually being used via the steam
#+overlay.
# 7: reserved for GIMP and other image editing programs that have excessive
#+floating windows.
# 8: Reserved for all videogames.
# 9: Reserved for the steam client, since it doesn't work very well when the
#+window is compressed.
# 10: Reserved for media applications and audio controls/setttings menus.

# ?: General
bspc rule -a 'File-roller' state=floating                                      &
bspc rule -a 'Nm-applet' layer=above                                           &
bspc rule -a 'URxvt:urxvtq' state=floating sticky=on                           &
bspc rule -a 'Firefox:Navigator' -o state=fullscreen						   &
bspc rule -a 'Firefox:Places' state=floating                                   &
bspc rule -a 'Firefox:Browser' state=floating                                  &
bspc rule -a 'Firefox:Toolkit' state=floating								   &
bspc rule -a 'steam' state=floating focus=off                                  &
bspc rule -a 'MuPDF' state=pseudo_tiled										   &
# 1: *
# 2: *
# 3: *
# 4: *
# 5: *
# 6: eMail/Messaging @
#bspc rule -a 'Thunderbird' desktop=^6                                         &
# 7: GIMP
# Make sure gimp is followed to desktop #7.
bspc rule -a 'Gimp' desktop=^7:primary follow=on							   &
# 8: Games
bspc rule -a 'Cockatrice' desktop=^8:primary								   &
bspc rule -a 'Openmw-launcher' desktop=^8:primary follow=on					   &
bspc rule -a 'openmw-launcher' desktop=^8:primary follow=on					   &
bspc rule -a 'openmw' desktop=^8:primary follow=on							   &
bspc rule -a 'quakespasm' desktop=^8:primary follow=on						   &
bspc rule -a 'quake2' desktop=^8:primary follow=on							   &
bspc rule -a 'ioquake3' desktop=^8:primary follow=on						   &
bspc rule -a 'csgo_linux64' desktop=^8:primary follow=on					   &
bspc rule -a 'dota2' desktop=^8:primary follow=on							   &
bspc rule -a 'dontstarve_steam' desktop=^8:primary follow=on				   &
bspc rule -a 'factorio' desktop=^8:primary follow=on						   &
bspc rule -a 'insurgency_linux' desktop=^8:primary follow=on				   &
bspc rule -a 'hl2_linux' desktop=^8:primary follow=on						   &
bspc rule -a 'dcg' desktop=^8:primary follow=on								   &
# 9: Steam takes up too much space so it gets it's own desktop.
bspc rule -a 'Steam' desktop=^9:primary										   &
# 10:Media
bspc rule -a 'Rhythmbox' desktop=^10:primary								   &
#bspc rule -a 'vlc' desktop=^10                                                &
#bspc rule -a 'Gnome-twitch' desktop=^10                                       &
bspc rule -a 'Pavucontrol' desktop=^10:primary								   &

# ============================================================================ #
#                  Startup Applications and Scripts - Post-Up                  #
# ============================================================================ #
# ---------------------------------------------------------------------------- #
#                 Daemons Only (Effects graphical applications)                #
# ---------------------------------------------------------------------------- #
# Start upstart, this should handle most daemons.
#upstart --user                                                                &

# Start compton compozitor.
# Usage: $1 optional set inactive opacity ON:0/off:1.
# Inactive opacity is set in: ~/.config/bspwm/restart_compton
$HOME/.config/bspwm/restart_compton 0                                          &

# Start gnome settings daemon.
# Applies GTK CSS settings and mouse settings.
#/usr/lib/gnome-settings-daemon/gnome-settings-daemon                          &

# Switch to dvorak keyboard layout.
# Do this in unity-control-center instead, it works more reliably with sxhkd.
#setxkbmap dvorak                                                              &

# ---------------------------------------------------------------------------- #
#             Daemons Only (Doesn't effect graphical applications)             #
# ---------------------------------------------------------------------------- #
# XFCE Power manager for backlight and keyboard backlight settings.
# Use: xfce4-power-manager-settings to configure.
#xfce4-power-manager                                                           &

# Start gnome keyring manager for SSH daemon.
#/usr/bin/gnome-keyring-daemon --start --components=ssh						   &

# Start indicator application daemon.
# Read here: https://launchpad.net/indicator-applet
# The indicator applet exposes Ayatana Indicators in the Gnome Panel.
#+Ayatana Indicators are an initiative by Canonical to provide crisp and clean
#+system and application status indication. They take the form of an icon and
#+associated menu, displayed (usually) in the desktop panel.
#+Existing indicators include the Message Menu, Battery Menu and Sound menu.
#/usr/lib/i386-linux-gnu/indicator-application/indicator-application-service   &

# Start PulseAudio and unmute the S/PDIF output, which is muted by default.
#pulseaudio --start && \
#amixer -c 0 sset IEC958 unmute                                                &


# ---------------------------------------------------------------------------- #
#                               Non-Daemons Only                               #
# ---------------------------------------------------------------------------- #
# Startup lemonbar script.
#$HOME/.config/bspwm/bar/panel                                                 &

# System menu applets.
# Start custom system menu written in python.
#${HOME}/Documents/Code/Python/SystemMenu.py								   &
# Start NetworkManager applet.
#nm-applet																	   &

# Put stalonetray on the right side of the screen in the middle.
# There is a keybind for this now.
#${HOME}/Documents/Code/Bash/toggle_stalonetray                                &

# ---------------------------------------------------------------------------- #
#                      Late Start Non-Essential Processes                      #
# ---------------------------------------------------------------------------- #
# Makes the default cursor the left pointer cursor instead of the X shaped one.
xsetroot -cursor_name left_ptr                                                 &
# Makes cursor disappear when idle.
unclutter -root -idle 10                                                       &

}

main &> ~/tmp/bspwmrc_error_messages.log

wait

exit 0
