#!/bin/bash

# ________________________________
#
# Name:
# restart_compton
#
# Usage:
# restart_compton
# restart_compton [0|1]
# (0:Inactive Opacity On | 1:Inactive Opacity Off)
#
# Description:
# Starts or restarts compton. Toggles inactive opactity on restart.
#
# Notes:
#
#
# Dependencies:
# compton
#
# ________________________________
#

# Usage:
# restart_compton
# restart_compton $1:'toggle inactive opacity'

# const
COMPTON_CONFIG="/home/jager/.config/bspwm/compton_config"
ACTIVE_OPACITY="0.7"
INACTIVE_OPACITY="0.6"
MENU_OPACITY="0.4"

# save current compton process args for later
# Don't change this to pgrep, it doesn't work.
condition_test=$(ps -ef | grep -e "compton -i" | grep -v "grep" | wc -l)
[[ $# -gt 0 ]] && condition_test=$1

# First, kill current compton instance
pkill -x --signal 9 compton
# Check if compton process was having -i option
# nohup is to detach compton process from the parent, run it as daemon
if [[ condition_test -gt 0 ]]; then
    # INACTIVE OPACTIY OFF
    compton \
    --config "${COMPTON_CONFIG}" -b &
else
    compton \
    -i "${INACTIVE_OPACITY}" \
	--active-opacity "${ACTIVE_OPACITY}" \
	--menu-opacity "${MENU_OPACITY}" \
    --config "${COMPTON_CONFIG}" -b \
	--blur-background \
	--blur-method kawase --blur-strength 10 &
fi

exit 0
